// Generated by gencpp from file polagraphe/TurnRequest.msg
// DO NOT EDIT!


#ifndef POLAGRAPHE_MESSAGE_TURNREQUEST_H
#define POLAGRAPHE_MESSAGE_TURNREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace polagraphe
{
template <class ContainerAllocator>
struct TurnRequest_
{
  typedef TurnRequest_<ContainerAllocator> Type;

  TurnRequest_()
    : Tr_L(0.0)
    , Tr_R(0.0)  {
    }
  TurnRequest_(const ContainerAllocator& _alloc)
    : Tr_L(0.0)
    , Tr_R(0.0)  {
  (void)_alloc;
    }



   typedef double _Tr_L_type;
  _Tr_L_type Tr_L;

   typedef double _Tr_R_type;
  _Tr_R_type Tr_R;





  typedef boost::shared_ptr< ::polagraphe::TurnRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::polagraphe::TurnRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TurnRequest_

typedef ::polagraphe::TurnRequest_<std::allocator<void> > TurnRequest;

typedef boost::shared_ptr< ::polagraphe::TurnRequest > TurnRequestPtr;
typedef boost::shared_ptr< ::polagraphe::TurnRequest const> TurnRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::polagraphe::TurnRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::polagraphe::TurnRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace polagraphe

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::polagraphe::TurnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::polagraphe::TurnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::polagraphe::TurnRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::polagraphe::TurnRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::polagraphe::TurnRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::polagraphe::TurnRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::polagraphe::TurnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3ff8c9a1f0ae9fb7b2591e1a6263fdb";
  }

  static const char* value(const ::polagraphe::TurnRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3ff8c9a1f0ae9fbULL;
  static const uint64_t static_value2 = 0x7b2591e1a6263fdbULL;
};

template<class ContainerAllocator>
struct DataType< ::polagraphe::TurnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "polagraphe/TurnRequest";
  }

  static const char* value(const ::polagraphe::TurnRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::polagraphe::TurnRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 Tr_L\n\
float64 Tr_R\n\
";
  }

  static const char* value(const ::polagraphe::TurnRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::polagraphe::TurnRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Tr_L);
      stream.next(m.Tr_R);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurnRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::polagraphe::TurnRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::polagraphe::TurnRequest_<ContainerAllocator>& v)
  {
    s << indent << "Tr_L: ";
    Printer<double>::stream(s, indent + "  ", v.Tr_L);
    s << indent << "Tr_R: ";
    Printer<double>::stream(s, indent + "  ", v.Tr_R);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POLAGRAPHE_MESSAGE_TURNREQUEST_H
